<?php

namespace AddUserDinoBundle\Repository;


/**
 * DinoMaterialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinoMaterialsRepository extends \Doctrine\ORM\EntityRepository
{


}
