<?php

namespace AddUserDinoBundle\Repository;


/**
 * DinoContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinoContentRepository extends \Doctrine\ORM\EntityRepository
{


}
