<?php

namespace AddUserDinoBundle\Repository;

use AddUserDinoBundle\Entity\DinoParameters;
use AddUserDinoBundle\Entity\User;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;


/**
 * DinoParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinoParametersRepository extends \Doctrine\ORM\EntityRepository
{
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('AddUserDinoBundle:DinoParameters')
            ->createQueryBuilder('p');

        return $qb;
    }

        /**
         * Tworzy obiekt DinoParameters i przypisuje mu startowe własności w zależności od wieku Dina
         * @param User $loggedUser
         * @return bool
         */
    public function setDinoParameters(User $loggedUser)
    {
        $dinoParameters = new DinoParameters();
        $loggedUserDinoAge = $loggedUser->getAge();

        $dinoParameters->setStrength(8+2*$loggedUserDinoAge);
        $dinoParameters->setSpeed(102-2*$loggedUserDinoAge);
        $dinoParameters->setHealth(69+$loggedUserDinoAge);
        $dinoParameters->setBackup(101-$loggedUserDinoAge);

        $loggedUser->setDino($dinoParameters);

        $em = $this->getDoctrine()->getManager();
        $em->persist($dinoParameters);
        $em->flush();

        return true;
    }

    public function findUserParameters($id) {

        $qb = $this->getQueryBuilder()
            ->select('p')
            ->from('AddUserDinoBundle:User', 'u')
            ->where('u.id = :val')
            ->setParameter('val', $id)
        ;

        return $qb->getQuery()->getResult();
    }


}
