<?php

namespace AddUserDinoBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPostsQueryBuilder($filter = '')
    {
        $qb =  $this->createQueryBuilder('post');

        if ($filter) {
            $qb->andWhere('post.title LIKE :filter')
                ->setParameter('filter', '%'.$filter.'%');
        }

        return $qb;
    }
}
