--
-- Zrzut danych tabeli `post`
--

INSERT INTO `post` (`id`, `created_at`, `updated_at`, `title`, `body`, `user_id`, `slug`) VALUES
(3, '2017-03-31 14:03:14', '2017-03-31 14:03:14', 'zwei', 'drei', 1, 'zwei'),
(5, '2017-03-31 14:08:50', '2017-03-31 14:08:50', 'tera gitarra', 'a jak', 1, 'tera-gitarra'),
(6, '2017-04-03 12:46:11', '2017-04-03 12:46:11', 'Lorem ipsum dolor sit amet', 'minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse', 1, 'lorem-ipsum-dolor-sit-amet'),
(7, '2017-04-03 12:46:39', '2017-04-03 12:46:39', 'Sed ut perspiciatis unde omnis', 'quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam', 1, 'sed-ut-perspiciatis-unde-omnis'),
(8, '2017-04-03 12:47:07', '2017-04-03 12:47:07', 'But I must explain to you', 'account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter', 1, 'but-i-must-explain-to-you'),
(9, '2017-04-03 12:47:26', '2017-04-03 12:47:26', 'At vero eos et accusamus', 'et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit', 1, 'at-vero-eos-et-accusamus'),
(10, '2017-04-03 12:47:50', '2017-04-03 12:47:50', 'On the other hand, we denounce', 'pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple', 1, 'on-the-other-hand-we-denounce'),
(11, '2017-04-03 12:48:13', '2017-04-03 12:48:13', 'aborum et dolorum fuga', 'optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat', 1, 'aborum-et-dolorum-fuga'),
(12, '2017-04-03 12:48:41', '2017-04-03 12:48:41', 'But I must explain to you how all this mistaken', 'Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"', 1, 'but-i-must-explain-to-you-how-all-this-mistaken'),
(13, '2017-04-03 12:49:21', '2017-04-03 12:49:21', 'But I must explain to you', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga', 1, 'but-i-must-explain-to-you-1'),
(14, '2017-04-03 12:49:49', '2017-04-03 12:49:49', 'Nemo enim ipsam', 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"', 1, 'nemo-enim-ipsam'),
(15, '2017-04-03 12:50:25', '2017-04-03 12:50:25', 'Lorem ipsum dolor', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.', 1, 'lorem-ipsum-dolor'),
(16, '2017-04-03 12:50:56', '2017-04-03 12:50:56', 'Nor again is there anyone', 'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."', 1, 'nor-again-is-there-anyone');

