<?php

namespace DinoBundle\Repository;

/**
 * DinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinoRepository extends \Doctrine\ORM\EntityRepository
{
}
