AdminEditUserNew:
    path: /blog/load_fresh_comments
    defaults: { _controller: AddUserDinoBundle:Blog/Comment:loadComments}

SendPdfEmail:
    path: /blog/send_pdf_email
    defaults: { _controller: AddUserDinoBundle:Blog/Post:sendPdf}